name: Checks

on: [push]

env:
  CI: true

jobs:
  ci:
    name: "Node ${{ matrix.node-version }}"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20, 22]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
      - run: npm run lint
        if: ${{ matrix.node-version == 22 }}
      - run: npm test
